In [1]:
import robosandbox as rsb
import numpy as np
import casadi as ca
import aerosandbox.numpy as anp
import aerosandbox as asb


In [2]:
t = np.array([0, 1, 2, 3]).T
print(t)

[0 1 2 3]


In [3]:
q = anp.array([0, 1, 2, 3]).T
print(q)

[0 1 2 3]


In [2]:
robot = rsb.models.MR.Generic.GenericFour()


In [10]:
theta_list = anp.array([0, 0.2, 0, 0.2])
Tlist = robot.fkine(theta_list)
%matplotlib qt
robot.plot_robot(Tlist)

x_axis: [1. 0. 0.]
x_axis: [1. 0. 0.]
x_axis: [-0.19866933  0.         -0.98006658]
x_axis: [-0.19866933  0.         -0.98006658]


In [21]:
theta_list = anp.array([0, 0.2, 0, 0.2])
Tlist = robot.fkine(theta_list)
print(Tlist[-1])
print(Tlist[-1][2, -1])

[[-0.38941834  0.92106099  0.          0.3147028 ]
 [ 0.          0.         -1.          0.        ]
 [-0.92106099 -0.38941834  0.          1.55247766]
 [ 0.          0.          0.          1.        ]]
1.5524776598741477


In [8]:
theta_list = anp.array([0, 0.2, 0, 0.2])
Tlist = robot.fkine(theta_list)

opti = asb.Opti()

q1 = opti.variable(init_guess=0.2) 
q2 = opti.variable(init_guess=0.2)
q3 = opti.variable(init_guess=0.2)
q4 = opti.variable(init_guess=0.2)

theta_list = anp.array([q1, q2, q3, q4])

f = robot.fkine(theta_list)[-1][2, -1]

opti.minimize(-f)
sol = opti.solve()

[[-0.38941834  0.92106099  0.          0.3147028 ]
 [ 0.          0.         -1.          0.        ]
 [-0.92106099 -0.38941834  0.          1.55247766]
 [ 0.          0.          0.          1.        ]]


In [22]:

opti = asb.Opti()

q1 = opti.variable(init_guess=0.2) 
q2 = opti.variable(init_guess=0.2)
q3 = opti.variable(init_guess=0.2)
q4 = opti.variable(init_guess=0.2)

# Define obj
f = robot.manipulability(q=[q1, q2, q3, q4], method='yoshikawa')

opti.minimize(f)
sol = opti.solve()


AttributeError: 'GenericFour' object has no attribute 'manipulability'